export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;


export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;

export const CHANGE_RANGE_SLIDER_VALUE = 'CHANGE_RANGE_SLIDER_VALUE';
export type CHANGE_RANGE_SLIDER_VALUE = typeof CHANGE_RANGE_SLIDER_VALUE;